// Mocks generated by Mockito 5.0.1 from annotations
// in test_app_1/test/two_digit_operation_test.dart.
// Do not manually edit this file.

import 'package:calculator/src/calculator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Calculator].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculator extends _i1.Mock implements _i2.Calculator {
  MockCalculator() {
    _i1.throwOnMissingStub(this);
  }
}
