name: test_app_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  calculator:
    path: packages/calculator

dev_dependencies:
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  mockito: ^5.0.1
  # test: ^1.16.6
  
    
flutter:
  uses-material-design: true
